server:
  port: 8080
  servlet:
    context-path: /identify

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/estatebasic"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true