server:
  port: 8080
  servlet:
    context-path: /identify

spring:
  profiles:
    active: dev

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"